SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `cotas` DEFAULT CHARACTER SET utf8 ;
USE `cotas` ;

-- -----------------------------------------------------
-- Table `cotas`.`Despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotas`.`Despesa` (
  `despesaId` INT(11) NOT NULL AUTO_INCREMENT,
  `codLegislatura` VARCHAR(500) NULL DEFAULT NULL,
  `datEmissao` VARCHAR(500) NULL DEFAULT NULL,
  `ideCadastro` VARCHAR(500) NULL DEFAULT NULL,
  `indTipoDocumento` VARCHAR(500) NULL DEFAULT NULL,
  `nuCarteiraParlamentar` VARCHAR(500) NULL DEFAULT NULL,
  `nuLegislatura` VARCHAR(500) NULL DEFAULT NULL,
  `numAno` VARCHAR(500) NULL DEFAULT NULL,
  `numEspecificacaoSubCota` VARCHAR(500) NULL DEFAULT NULL,
  `numLote` VARCHAR(500) NULL DEFAULT NULL,
  `numMes` VARCHAR(500) NULL DEFAULT NULL,
  `numParcela` VARCHAR(500) NULL DEFAULT NULL,
  `numRessarcimento` VARCHAR(500) NULL DEFAULT NULL,
  `numSubCota` VARCHAR(500) NULL DEFAULT NULL,
  `sgPartido` VARCHAR(500) NULL DEFAULT NULL,
  `sgUF` VARCHAR(500) NULL DEFAULT NULL,
  `txNomeParlamentar` VARCHAR(500) NULL DEFAULT NULL,
  `txtCNPJCPF` VARCHAR(500) NULL DEFAULT NULL,
  `txtDescricao` VARCHAR(500) NULL DEFAULT NULL,
  `txtDescricaoEspecificacao` VARCHAR(500) NULL DEFAULT NULL,
  `txtFornecedor` VARCHAR(500) NULL DEFAULT NULL,
  `txtNumero` VARCHAR(500) NULL DEFAULT NULL,
  `txtPassageiro` VARCHAR(500) NULL DEFAULT NULL,
  `txtTrecho` VARCHAR(500) NULL DEFAULT NULL,
  `vlrDocumento` VARCHAR(500) NULL DEFAULT NULL,
  `vlrGlosa` VARCHAR(500) NULL DEFAULT NULL,
  `vlrLiquido` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`despesaId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1578402;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
